# Generated by Django 5.2.4 on 2025-07-05 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_description_aisuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextentry',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='context_entries', to='todo.task'),
        ),
    ]
